=== Vanessa2300/WT/employee_details.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (employee_id, first_name, last_name, email, department, salary)>
<!ELEMENT employee_id (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== Vanessa2300/WT/employee_details.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee_details.dtd">
<employees>
  <employee>
    <employee_id>101</employee_id>
    <first_name>Jane</first_name>
    <last_name>Will</last_name>
    <email>abcdef@email.com</email>
    <department>Software Engineer</department>
    <salary>55000</salary>
  </employee>

  <employee>
    <employee_id>102</employee_id>
    <first_name>Kiara</first_name>
    <last_name>Smith</last_name>
    <email>xyz@example.com</email>
    <department>HR</department>
    <salary>60000</salary>
  </employee>
</employees>
