<!DOCTYPE real-estate [
  <!ELEMENT real-estate (agencies, owners, properties, flats)>
  <!ELEMENT agencies EMPTY>
  <!ELEMENT owners EMPTY>
  <!ELEMENT properties EMPTY>
  <!ELEMENT flats EMPTY>
]>
<real-estate> <!--Remove this line to cause validity issue-->
  <agencies></agencies>
  <owners></owners>
  <properties></properties>
  <flats></flats>
</real-estate>
